# Generated by Django 3.1.6 on 2021-02-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_auth', '0004_auto_20210209_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicuser',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
