# Generated by Django 3.1.6 on 2021-02-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicuser',
            name='auth_token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
